inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

Style/BlockComments:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/Void:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
